---

- name: Add HashiCorp Vault's ubuntu repository
  block:

  - name: vault ubuntu repo key
    ansible.builtin.get_url:
      url: https://apt.releases.hashicorp.com/gpg
      dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    environment:
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

  - name: Add an Apt signing key, uses whichever key is at the URL
    ansible.builtin.apt_key:
      url: https://apt.releases.hashicorp.com/gpg
      state: present
    environment:
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

  - name: vault ubuntu repo
    # ansible.builtin.apt_repository:
    apt_repository:
    # repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/somerepo.asc] https://download.example.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
      state: present
    environment:
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

  when: vault_install_from_repository | default('true') | bool


- name: Install Vault from a local package
  block:

  - name: Copy package to remote host
    copy:
      src: "files/{{ vault_package_name }}"
      dest: "/tmp/{{ vault_package_name }}"

  - name: Install vault package
    apt:
      deb: "/tmp/{{ vault_package_name }}"

  - name: Clean up package data
    file:
      path: "/tmp/{{ vault_package_name }}"
      state: absent